spring:
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
  application:
    name: @project.name@
  cloud:
    config:
      enabled: false
  config:
    import:
      - 'optional:configserver:'
      - classpath:/server.yml
      - classpath:/kloudy.yml
      - classpath:/management.yml
      - classpath:/security.yml
      - classpath:/eureka.yml
      - classpath:/keycloak.yml
      - classpath:/logging.yml
      - classpath:/springdoc.yml
  devtools:
    restart:
      enabled: false
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  data:
    jdbc:
      dialect: postgresql
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      org:
        hibernate:
          envers:
            audit_strategy: org.hibernate.envers.strategy.ValidityAuditStrategy
            default_schema: history
            audit_table_suffix: _history
            revision_field_name: rev_id
            revision_type_field_name: rev_type
            store_data_at_delete: true
      #            audit_table_prefix:
      hibernate:
        enable_lazy_load_no_trans: true
        default_schema: kloudy
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
