server:
  port: 8901
  servlet:
    context-path: /api
    application-display-name: "Kloudy - FS storage"
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: always
  tomcat:
    max-swallow-size: 0
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientAutoConfiguration
  web:
    locale: en
    resources:
      chain:
        compressed: true
      cache:
        cachecontrol:
          max-age: 3600
          must-revalidate: true
  mvc:
    problemdetails:
      enabled: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      file-size-threshold: 2MB
      location: ${java.io.tmpdir}
  application:
    name: kloudy
  cloud:
    config:
      enabled: false
    bus:
      enabled: false
  rabbitmq:
    enabled: false
  devtools:
    restart:
      enabled: false
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  jpa:
    properties:
      org:
        hibernate:
          envers:
            audit_strategy: org.hibernate.envers.strategy.ValidityAuditStrategy
            audit_table_suffix: _history
            revision_field_name: rev_id
            revision_type_field_name: rev_type
            store_data_at_delete: true
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      client:
        enabled: false
management:
  server:
    port: -1
springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
