server:
  port: 8901
  servlet:
    context-path: /api
    application-display-name: "Kloudy - FS storage"
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: always
  tomcat:
    max-swallow-size: 0
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
  web:
    locale: en
    resources:
      chain:
        compressed: true
      cache:
        cachecontrol:
          max-age: 3600
          must-revalidate: true
  mvc:
    problemdetails:
      enabled: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      file-size-threshold: 2MB
      location: ${java.io.tmpdir}
  application:
    name: kloudy
  cloud:
    config:
      enabled: false
    bus:
      enabled: false
    discovery:
      enabled: false
  rabbitmq:
    enabled: false
  devtools:
    restart:
      enabled: false
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  security:
    user:
      name: kloudy
    oauth2:
      client:
        enabled: false
      resourceserver:
        enabled: false
management:
  server:
    port: -1
springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
eureka:
  client:
    enabled: false
kloudy:
  store:
    bucket: ${user.home}/.kloudy.bucket.d
