spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.issuer-uri}
          jwk-set-uri: ${keycloak.jwk-set-uri}
        opaquetoken:
          introspection-uri: ${keycloak.introspection-uri}
          client-id: ${keycloak.client-id}
          client-secret: ${keycloak.client-secret}
    user:
      name: ${USERNAME:justedlev}
      password: ${PASSWORD:{example}}
      roles: ${ROLES:system}
security:
  whitelist:
    GET:
      - /webjars/**
      - /v3/api-docs/**
      - /*/v3/api-docs/**
      - /*/*/v3/api-docs/**
      - /swagger-ui.html
      - /swagger-ui/**
      - /swagger-resources
      - /swagger-resources/**
      - /configuration/ui
      - /configuration/security
      - /actuator/**
      - /*/actuator/**
      - /error
    POST:
      - /sso/logout
      - /logout
