name: justedlev-msrv
services:
  fss.justedlev.io:
    tty: true
    container_name: kloudy
    image: justedlev/kloudy:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8901:5000"
      - "7901:7000"
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 512MB
    volumes:
      - kloudy_bucket:/home/kloudy/kloudy.bucket.d
volumes:
  kloudy_bucket:
